// app/pages/humanizer/index.vue
<template>
  <div class="space-y-8">
    <div>
      <h1 class="text-xl font-semibold text-fg-neutral">휴머나이저</h1>
      <p class="text-xs text-fg-neutral-muted mt-0.5">AI 문체를 자연스러운 인간 어조로 변환합니다</p>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <div class="rounded-xl border border-stroke-neutral-muted p-6 bg-neutral-muted space-y-4">
        <h3 class="text-sm font-medium text-fg-neutral">원본 문장</h3>
        <UTextarea v-model="originalText" :rows="12" placeholder="교정할 문장을 입력하세요..." />
        <UButton color="black" variant="solid" size="lg" class="w-full" :loading="loading" :disabled="!originalText.trim()" label="변환" @click="processHumanize" />
      </div>

      <div class="rounded-xl border border-stroke-neutral-muted p-6 bg-neutral-muted space-y-4">
        <h3 class="text-sm font-medium text-fg-neutral">변환 결과</h3>
        <div v-if="result" class="space-y-4">
          <div class="flex items-center justify-between">
            <span class="text-xs text-fg-neutral-muted">자연스러움</span>
            <span class="text-base font-medium text-fg-neutral">{{ result.styleScore }}</span>
          </div>
          <div class="p-4 rounded-lg bg-neutral-muted text-sm text-fg-neutral leading-relaxed whitespace-pre-wrap">{{ result.humanizedText }}</div>
          <div class="p-4 rounded-lg bg-neutral-muted text-xs space-y-2">
            <div class="font-medium text-fg-neutral-muted">변환 요약</div>
            <p class="text-fg-neutral-muted">{{ result.changesSummary }}</p>
            <div v-if="result.removedClichés && result.removedClichés.length > 0" class="flex flex-wrap gap-1.5 pt-1">
              <UBadge v-for="(c, idx) in result.removedClichés" :key="idx" color="red" variant="soft" size="xs"><s>{{ c }}</s></UBadge>
            </div>
          </div>
        </div>
        <div v-else class="h-64 flex items-center justify-center text-center text-fg-neutral-muted">
          <p class="text-xs">문장을 입력하고 변환 버튼을 누르세요</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const toast = useToast()
const originalText = ref('본 지원자는 지난 3년간 웹 프론트엔드 개발 프로젝트 수행에 있어 프론트엔드 성능 최적화 관점에서 다각도로 접근하여 효율적인 리팩토링을 완수함에 있어 큰 성과를 거두었습니다.')
const loading = ref(false)
const result = ref<any>(null)

async function processHumanize() {
  if (!originalText.value.trim()) return
  loading.value = true
  try {
    const res: any = await $fetch('/api/humanizer/process', { method: 'POST', body: { originalText: originalText.value } })
    result.value = res
  } catch (err: any) {
    toast.add({ title: '변환 실패', description: err.data?.message || '휴머나이저 변환 중 오류가 발생했습니다.', color: 'red' })
  }
  finally { loading.value = false }
}
</script>

// src/app/(authenticated)/humanizer/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useToast } from '@/lib/toast';
import Spinner from '@/components/Spinner';

export default function HumanizerPage() {
  const toast = useToast();
  const [inputText, setInputText] = useState('');
  const [outputText, setOutputText] = useState('');
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState<any[]>([]);
  const [styleScore, setStyleScore] = useState<number | null>(null);

  useEffect(() => {
    fetch('/api/humanizer/history').then(r => r.ok ? r.json() : []).then(d => setHistory(d || [])).catch(() => {});
  }, []);

  async function humanize() {
    if (!inputText.trim()) return;
    setLoading(true);
    setOutputText('');
    setStyleScore(null);
    try {
      const res = await fetch('/api/humanizer/process', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: inputText }),
      });
      if (res.ok) {
        const data = await res.json();
        setOutputText(data.humanizedText || '');
        setStyleScore(data.styleScore || null);
        if (data.id) setHistory(prev => [data, ...prev]);
      }
    } catch (err: any) {
      toast.add({ title: 'Error', description: err.message, color: 'red' });
    } finally {
      setLoading(false);
    }
  }

  function copyToClipboard() {
    navigator.clipboard.writeText(outputText);
    toast.add({ title: 'Copied!', color: 'green' });
  }

  return (
    <div className="space-y-8">
      <div>
        <p className="text-xs font-semibold tracking-widest text-blue-500 uppercase mb-1">AI Humanizer</p>
        <h1 className="text-2xl font-bold text-gray-900 tracking-tight">AI Text Humanizer</h1>
        <p className="text-sm text-gray-500 mt-1">Transform AI-generated text to sound natural and human</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <label className="text-xs font-bold text-gray-500 uppercase tracking-wide">Input (AI text)</label>
            <span className="text-xs text-gray-400">{inputText.length} chars</span>
          </div>
          <textarea
            rows={14}
            value={inputText}
            onChange={e => setInputText(e.target.value)}
            placeholder="Paste AI-generated text here..."
            className="w-full px-4 py-3.5 rounded-2xl border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-400 resize-none leading-relaxed"
          />
          <button
            onClick={humanize}
            disabled={loading || !inputText.trim()}
            className="w-full py-3 bg-blue-600 text-white text-sm font-semibold rounded-xl hover:bg-blue-700 transition-colors disabled:opacity-40 flex items-center justify-center gap-2"
          >
            {loading && <Spinner className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />}
            {loading ? 'Processing...' : 'Humanize Text'}
          </button>
        </div>

        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <label className="text-xs font-bold text-gray-500 uppercase tracking-wide">Output (Human text)</label>
            {styleScore !== null && (
              <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2.5 py-1 rounded-full border border-emerald-100">
                Naturalness: {styleScore}%
              </span>
            )}
          </div>
          <div className="relative">
            <textarea
              rows={14}
              value={outputText}
              readOnly
              placeholder="Humanized text will appear here..."
              className="w-full px-4 py-3.5 rounded-2xl border border-gray-200 text-sm bg-gray-50/50 resize-none leading-relaxed"
            />
            {outputText && (
              <button
                onClick={copyToClipboard}
                className="absolute top-3 right-3 px-3 py-1.5 text-xs font-semibold bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600 transition-colors shadow-xs"
              >
                Copy
              </button>
            )}
          </div>
        </div>
      </div>

      {history.length > 0 && (
        <div className="bg-white rounded-2xl border border-gray-100 shadow-xs overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-100">
            <h2 className="text-sm font-semibold text-gray-700">History</h2>
          </div>
          <div className="divide-y divide-gray-50">
            {history.slice(0, 5).map((h: any) => (
              <div key={h.id} className="px-6 py-4 flex items-start gap-4 hover:bg-gray-50/50 transition-colors">
                <div className="flex-1 min-w-0">
                  <p className="text-xs text-gray-500 truncate">{h.originalText}</p>
                  <p className="text-xs font-medium text-gray-800 truncate mt-1">{h.humanizedText}</p>
                </div>
                {h.styleScore && (
                  <span className="shrink-0 text-xs font-bold text-emerald-600">{h.styleScore}%</span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
