// src/components/Navbar.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useAuth } from '@/context/AuthContext';
import LogoImage from './LogoImage';

export default function Navbar() {
  const pathname = usePathname();
  const { state, logout } = useAuth();
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setDropdownOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  return (
    <header className="sticky top-0 z-40 bg-slate-900/90 backdrop-blur-md border-b border-slate-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between gap-4">
        {/* Brand Logo */}
        <Link href="/" className="flex items-center gap-2.5 group">
          <LogoImage style={{ width: 32, height: 32 }} />
          <span className="font-bold text-lg text-white tracking-tight group-hover:text-indigo-400 transition-colors">
            Kairos <span className="text-xs font-semibold px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">AI OS</span>
          </span>
        </Link>

        {/* Navigation Links */}
        <nav className="hidden md:flex items-center gap-6 text-sm font-medium">
          <Link href="/resume" className={`hover:text-indigo-400 transition-colors ${pathname.startsWith('/resume') ? 'text-indigo-400 font-semibold' : 'text-slate-300'}`}>
            AI 이력서
          </Link>
          <Link href="/interview" className={`hover:text-indigo-400 transition-colors ${pathname.startsWith('/interview') ? 'text-indigo-400 font-semibold' : 'text-slate-300'}`}>
            모의면접
          </Link>
          <Link href="/ats" className={`hover:text-indigo-400 transition-colors ${pathname.startsWith('/ats') ? 'text-indigo-400 font-semibold' : 'text-slate-300'}`}>
            ATS 분석
          </Link>
          <Link href="/humanizer" className={`hover:text-indigo-400 transition-colors ${pathname.startsWith('/humanizer') ? 'text-indigo-400 font-semibold' : 'text-slate-300'}`}>
            Humanizer
          </Link>
        </nav>

        {/* Right Section / Auth */}
        <div className="flex items-center gap-3">
          {state.authenticated && state.user ? (
            <div className="relative" ref={dropdownRef}>
              <button
                onClick={() => setDropdownOpen(!dropdownOpen)}
                className="flex items-center gap-2 p-1.5 rounded-full hover:bg-slate-800 transition-colors"
              >
                <img
                  src={state.user.avatarUrl || 'https://ui-avatars.com/api/?name=User'}
                  alt={state.user.name}
                  className="w-8 h-8 rounded-full border border-indigo-500/40 object-cover"
                />
                <span className="text-sm font-medium text-slate-200 hidden sm:inline">{state.user.name}</span>
                <svg className="w-4 h-4 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                </svg>
              </button>

              {dropdownOpen && (
                <div className="absolute right-0 mt-2 w-56 bg-slate-900 border border-slate-800 rounded-xl shadow-xl py-2 z-50">
                  <div className="px-4 py-2 border-b border-slate-800">
                    <p className="text-sm font-semibold text-white">{state.user.name}</p>
                    <p className="text-xs text-slate-400 truncate">{state.user.email}</p>
                  </div>
                  <Link
                    href="/settings"
                    className="flex items-center gap-2 px-4 py-2 text-sm text-slate-300 hover:bg-slate-800 hover:text-white"
                    onClick={() => setDropdownOpen(false)}
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                    </svg>
                    <span>설정</span>
                  </Link>
                  <hr className="my-1 border-slate-800" />
                  <button
                    onClick={() => { setDropdownOpen(false); logout(); }}
                    className="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-400 hover:bg-slate-800 text-left"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                    </svg>
                    <span>로그아웃</span>
                  </button>
                </div>
              )}
            </div>
          ) : (
            <Link
              href="/auth/login"
              className="px-4 py-2 text-sm font-medium bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors"
            >
              로그인
            </Link>
          )}
        </div>
      </div>
    </header>
  );
}

// app/components/Navbar.vue
<template>
  <header class="sticky top-0 z-40 border-b border-gray-100 bg-white/90 backdrop-blur-xl">
    <div class="flex items-center justify-between h-14 px-4 sm:px-6 max-w-screen-xl mx-auto">
      <!-- Logo -->
      <div class="flex items-center gap-2.5">
        <!-- Mobile: hamburger -->
        <button
          v-if="state.authenticated"
          @click="$emit('toggleDrawer')"
          class="lg:hidden w-8 h-8 flex items-center justify-center rounded-lg text-gray-500 hover:bg-gray-100 transition-colors mr-1"
          aria-label="메뉴 열기"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
          </svg>
        </button>

        <NuxtLink to="/" class="flex items-center gap-2">
          <LogoImage img-class="h-6 w-auto object-contain" style="filter: brightness(0);" />
        </NuxtLink>
      </div>

      <!-- Desktop nav (unauthenticated) -->
      <nav v-if="!state.authenticated" class="hidden md:flex items-center gap-6 text-sm text-gray-500">
        <a href="#features" class="hover:text-gray-900 transition-colors">기능</a>
        <NuxtLink to="/auth/login" class="hover:text-gray-900 transition-colors">로그인</NuxtLink>
        <NuxtLink to="/auth/register" class="px-4 py-1.5 rounded-xl bg-gray-900 text-white text-sm font-semibold hover:bg-indigo-700 transition-colors">
          시작하기
        </NuxtLink>
      </nav>

      <!-- Desktop nav (authenticated) -->
      <nav v-else-if="state.authenticated" class="hidden lg:flex items-center gap-5 text-sm text-gray-500">
        <NuxtLink to="/resume" class="hover:text-gray-900 transition-colors" :class="route.path.startsWith('/resume') ? 'text-indigo-600 font-semibold' : ''">이력서</NuxtLink>
        <NuxtLink to="/interview" class="hover:text-gray-900 transition-colors" :class="route.path.startsWith('/interview') ? 'text-indigo-600 font-semibold' : ''">면접</NuxtLink>
        <NuxtLink to="/ats" class="hover:text-gray-900 transition-colors" :class="route.path.startsWith('/ats') ? 'text-indigo-600 font-semibold' : ''">ATS</NuxtLink>
        <NuxtLink to="/career" class="hover:text-gray-900 transition-colors" :class="route.path.startsWith('/career') ? 'text-indigo-600 font-semibold' : ''">경력</NuxtLink>
      </nav>

      <!-- Right actions -->
      <div class="flex items-center gap-2">
        <!-- Authenticated user avatar -->
        <div v-if="state.authenticated && state.user" class="relative">
          <button
            class="flex items-center gap-2 cursor-pointer hover:opacity-80 transition-opacity"
            @click="menuOpen = !menuOpen"
          >
            <img
              :src="state.user.avatarUrl || 'https://ui-avatars.com/api/?name=' + encodeURIComponent(state.user.name || 'U') + '&background=e0e7ff&color=4f46e5&size=64'"
              :alt="state.user.name"
              class="w-8 h-8 rounded-full border-2 border-gray-100 object-cover"
            />
            <span class="hidden md:inline text-sm font-medium text-gray-700">{{ state.user.name }}</span>
            <svg class="hidden md:block w-3.5 h-3.5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
          </button>

          <!-- Dropdown -->
          <Transition name="fade-down">
            <div v-if="menuOpen" class="absolute top-full right-0 mt-2 w-48 rounded-2xl border border-gray-100 bg-white shadow-lg py-2 z-50">
              <div class="px-4 py-2 border-b border-gray-100 mb-1">
                <p class="text-xs font-bold text-gray-900 truncate">{{ state.user.name }}</p>
                <p class="text-xs text-gray-400 truncate">{{ state.user.email }}</p>
              </div>
              <NuxtLink to="/settings" class="flex items-center gap-2.5 px-4 py-2 text-sm text-gray-600 hover:bg-gray-50 hover:text-gray-900 transition-colors" @click="menuOpen = false">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
                설정
              </NuxtLink>
              <hr class="my-1 border-gray-100" />
              <button class="flex items-center gap-2.5 w-full text-left px-4 py-2 text-sm text-red-500 hover:bg-red-50 transition-colors" @click="handleLogout">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"/></svg>
                로그아웃
              </button>
            </div>
          </Transition>
        </div>

        <!-- Not authenticated on mobile -->
        <NuxtLink
          v-else-if="!state.loading"
          to="/auth/login"
          class="text-sm font-semibold text-gray-600 hover:text-gray-900 transition-colors"
        >로그인</NuxtLink>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
defineEmits(['toggleDrawer'])
const { state, fetchUser, logout } = useAuth()
const route = useRoute()
const menuOpen = ref(false)

onMounted(() => { fetchUser() })

function handleLogout() {
  menuOpen.value = false
  logout()
}

// Close dropdown on outside click
onMounted(() => {
  document.addEventListener('click', (e) => {
    if (!(e.target as HTMLElement).closest('.relative')) {
      menuOpen.value = false
    }
  })
})
</script>

<style scoped>
.fade-down-enter-active, .fade-down-leave-active { transition: all 0.15s ease; }
.fade-down-enter-from { opacity: 0; transform: translateY(-6px); }
.fade-down-leave-to { opacity: 0; transform: translateY(-6px); }
</style>
