// src/components/ThinkingBubble.tsx
'use client';

interface ThinkingBubbleProps {
  active?: boolean;
  step?: number;
  totalSteps?: number;
  stepTitle?: string;
  thinkingDetails?: string;
}

export default function ThinkingBubble({
  active = false,
  step = 1,
  totalSteps = 3,
  stepTitle = 'AI 심층 추론 중...',
  thinkingDetails,
}: ThinkingBubbleProps) {
  if (!active) return null;

  const percent = Math.min(100, Math.round((step / totalSteps) * 100));

  return (
    <div className="my-4 p-4 rounded-xl bg-slate-900/80 border border-indigo-500/30 text-indigo-200 backdrop-blur-sm animate-pulse">
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <span className="inline-block w-2 h-2 rounded-full bg-indigo-400 animate-ping" />
          <span className="font-semibold text-sm text-indigo-300">{stepTitle}</span>
        </div>
        <span className="text-xs text-indigo-400 font-mono">
          Step {step}/{totalSteps} ({percent}%)
        </span>
      </div>

      <div className="w-full bg-slate-800 rounded-full h-1.5 overflow-hidden mb-2">
        <div
          className="bg-gradient-to-r from-indigo-500 to-purple-500 h-full transition-all duration-300"
          style={{ width: `${percent}%` }}
        />
      </div>

      {thinkingDetails && (
        <p className="text-xs text-slate-400 font-mono line-clamp-2 leading-relaxed">
          {thinkingDetails}
        </p>
      )}
    </div>
  );
}

// app/components/ThinkingBubble.vue
<template>
  <div v-if="active" class="rounded-lg border border-purple-500/20 bg-purple-950/20 p-3.5 space-y-2.5 backdrop-blur-sm transition-all duration-300">
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-2">
        <div class="relative flex h-2.5 w-2.5">
          <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-purple-400 opacity-75"></span>
          <span class="relative inline-flex rounded-full h-2.5 w-2.5 bg-purple-500"></span>
        </div>
        <span class="text-xs font-semibold text-purple-300 tracking-wide uppercase">Kairos AI Thinking Engine</span>
      </div>
      <span class="text-[10px] text-purple-400 font-mono">Step {{ step }}/{{ totalSteps }}</span>
    </div>

    <!-- Thinking Message & Animation -->
    <div class="flex items-start gap-2.5 text-xs text-purple-200/90 leading-relaxed">
      <div class="pt-0.5">
        <UIcon name="i-lucide-brain-circuit" class="w-4 h-4 text-purple-400 animate-pulse" />
      </div>
      <div class="flex-1 space-y-1">
        <p class="font-medium">{{ stepTitle }}</p>
        <p v-if="thinkingDetails" class="text-[11px] text-purple-300/70 font-mono leading-normal whitespace-pre-wrap line-clamp-3">
          {{ thinkingDetails }}
        </p>
      </div>
    </div>

    <!-- Progress Bar -->
    <div class="w-full bg-purple-950/60 rounded-full h-1 overflow-hidden">
      <div 
        class="bg-gradient-to-r from-purple-500 via-indigo-500 to-cyan-400 h-full transition-all duration-500"
        :style="{ width: `${(step / totalSteps) * 100}%` }"
      ></div>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  active?: boolean
  step?: number
  totalSteps?: number
  stepTitle?: string
  thinkingDetails?: string
}

withDefaults(defineProps<Props>(), {
  active: false,
  step: 1,
  totalSteps: 3,
  stepTitle: '의도 파악 및 경험 벡터 매칭 중...',
  thinkingDetails: '',
})
</script>
