// src/app/(authenticated)/ats/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import { useToast } from '@/lib/toast';

export default function ATSPage() {
  const toast = useToast();

  const [jobTitle, setJobTitle] = useState('');
  const [jobDescription, setJobDescription] = useState('');
  const [resumeText, setResumeText] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [resumes, setResumes] = useState<any[]>([]);
  const [selectedResumeId, setSelectedResumeId] = useState('');

  useEffect(() => {
    fetch('/api/resumes').then(r => r.ok ? r.json() : []).then(d => setResumes(d || [])).catch(() => {});
  }, []);

  function onResumeSelect(id: string) {
    setSelectedResumeId(id);
    const found = resumes.find(r => r.id === id);
    if (found) setResumeText(found.originalContent || '');
  }

  async function analyze() {
    setLoading(true);
    setResult(null);
    try {
      const res = await fetch('/api/ats/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ jobTitle, jobDescription, resumeText, resumeId: selectedResumeId || undefined }),
      });
      if (res.ok) setResult(await res.json());
    } catch (err: any) {
      toast.add({ title: 'Error', description: err.message, color: 'red' });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-8">
      <div>
        <p className="text-xs font-semibold tracking-widest text-blue-500 uppercase mb-1">ATS Match</p>
        <h1 className="text-2xl font-bold text-gray-900 tracking-tight">ATS Matching Analysis</h1>
        <p className="text-sm text-gray-500 mt-1">AI analyzes keyword matching between JD and resume</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-5">
          <div className="bg-white rounded-2xl border border-gray-100 shadow-xs p-5 space-y-4">
            <h2 className="text-sm font-semibold text-gray-700">Job Description</h2>
            <div>
              <label className="block text-xs font-semibold text-gray-500 mb-1.5">Job Title</label>
              <input type="text" value={jobTitle} onChange={e => setJobTitle(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-xl border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-400" />
            </div>
            <div>
              <label className="block text-xs font-semibold text-gray-500 mb-1.5">Requirements</label>
              <textarea rows={6} value={jobDescription} onChange={e => setJobDescription(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-xl border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-400 resize-none" />
            </div>
          </div>
          <div className="bg-white rounded-2xl border border-gray-100 shadow-xs p-5 space-y-4">
            <h2 className="text-sm font-semibold text-gray-700">Resume</h2>
            {resumes.length > 0 && (
              <select value={selectedResumeId} onChange={e => onResumeSelect(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-xl border border-gray-200 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-400">
                <option value="">Manual input</option>
                {resumes.map(r => <option key={r.id} value={r.id}>{r.title}</option>)}
              </select>
            )}
            <textarea rows={8} value={resumeText} onChange={e => setResumeText(e.target.value)}
              placeholder="Paste resume text here..."
              className="w-full px-3.5 py-2.5 rounded-xl border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-400 resize-none" />
            <button onClick={analyze} disabled={loading || !jobDescription || !resumeText}
              className="w-full py-3 rounded-xl bg-blue-600 text-white text-sm font-semibold hover:bg-blue-700 transition-colors disabled:opacity-40 flex items-center justify-center gap-2">
              {loading && <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />}
              {loading ? 'Analyzing...' : 'Start ATS Analysis'}
            </button>
          </div>
        </div>

        <div>
          {!result ? (
            <div className="bg-white rounded-2xl border border-dashed border-gray-200 p-16 flex flex-col items-center justify-center gap-3 text-center h-full">
              <div className="w-16 h-16 bg-blue-50 rounded-2xl flex items-center justify-center text-2xl">📊</div>
              <p className="text-sm font-medium text-gray-600">Results will appear here</p>
            </div>
          ) : (
            <div className="space-y-5">
              <div className="bg-white rounded-2xl border border-gray-100 shadow-xs p-6 text-center">
                <div className="w-28 h-28 rounded-full bg-gradient-to-br from-blue-400 to-indigo-400 p-1 mx-auto">
                  <div className="w-full h-full rounded-full bg-white flex flex-col items-center justify-center">
                    <div className="text-3xl font-black text-blue-600">{result.matchScore}</div>
                    <div className="text-xs text-gray-400 font-medium">/ 100</div>
                  </div>
                </div>
                <p className="text-sm font-semibold text-gray-700 mt-3">ATS Match Score</p>
              </div>
              {result.missingKeywords?.length > 0 && (
                <div className="bg-white rounded-2xl border border-gray-100 shadow-xs p-5">
                  <h3 className="text-xs font-bold text-red-500 uppercase tracking-wide mb-3">Missing Keywords</h3>
                  <div className="flex flex-wrap gap-2">
                    {result.missingKeywords.map((kw: string) => (
                      <span key={kw} className="px-2.5 py-1 bg-red-50 text-red-600 text-xs font-semibold rounded-full border border-red-100">{kw}</span>
                    ))}
                  </div>
                </div>
              )}
              {result.foundKeywords?.length > 0 && (
                <div className="bg-white rounded-2xl border border-gray-100 shadow-xs p-5">
                  <h3 className="text-xs font-bold text-emerald-600 uppercase tracking-wide mb-3">Matched Keywords</h3>
                  <div className="flex flex-wrap gap-2">
                    {result.foundKeywords.map((kw: string) => (
                      <span key={kw} className="px-2.5 py-1 bg-emerald-50 text-emerald-600 text-xs font-semibold rounded-full border border-emerald-100">{kw}</span>
                    ))}
                  </div>
                </div>
              )}
              {result.recommendations?.length > 0 && (
                <div className="bg-white rounded-2xl border border-gray-100 shadow-xs p-5">
                  <h3 className="text-xs font-bold text-blue-600 uppercase tracking-wide mb-3">Recommendations</h3>
                  <ul className="space-y-2">
                    {result.recommendations.map((rec: string, i: number) => (
                      <li key={i} className="flex items-start gap-2 text-xs text-gray-600">
                        <span className="mt-1 shrink-0 w-4 h-4 rounded-full bg-blue-50 text-blue-500 flex items-center justify-center font-bold text-[10px]">{i + 1}</span>
                        {rec}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// app/pages/ats/index.vue
<template>
  <div class="max-w-6xl mx-auto py-10 space-y-10 px-4 pb-20">
    <!-- Header -->
    <div class="pb-6 border-b border-slate-100">
      <h1 class="text-3xl font-extrabold text-slate-900 tracking-tight">AI ATS 적합성 매칭</h1>
      <p class="text-sm font-medium text-slate-400 mt-2">채용 공고(JD)의 요구 스택 및 우대사항을 AI 기반으로 파싱하여 이력서와의 직무 적합률을 분석합니다.</p>
    </div>

    <!-- Inputs Group -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <!-- JD Input Card -->
      <div class="bg-white border border-slate-100 rounded-3xl p-6 sm:p-8 shadow-sm space-y-5">
        <div class="flex items-center gap-2 pb-3 border-b border-slate-50">
          <UIcon name="i-lucide-briefcase" class="w-5 h-5 text-blue-600" />
          <h3 class="text-base font-bold text-slate-800">채용 정보 (Job Description)</h3>
        </div>

        <UFormGroup label="직무명">
          <UInput v-model="jobTitle" size="md" placeholder="예: 시니어 프론트엔드 개발자" class="w-full" />
        </UFormGroup>

        <UFormGroup label="자격요건 및 요구 스택">
          <UTextarea v-model="jobDescription" :rows="10" placeholder="채용공고의 자격요건, 우대사항 등 본문을 여기에 붙여넣으세요..." class="w-full font-mono text-sm leading-relaxed" />
        </UFormGroup>
      </div>

      <!-- Resume Selection & Input Card -->
      <div class="bg-white border border-slate-100 rounded-3xl p-6 sm:p-8 shadow-sm space-y-5 flex flex-col justify-between">
        <div class="space-y-5">
          <div class="flex items-center justify-between pb-3 border-b border-slate-55">
            <div class="flex items-center gap-2">
              <UIcon name="i-lucide-file-text" class="w-5 h-5 text-blue-600" />
              <h3 class="text-base font-bold text-slate-800">대상 이력서 선택</h3>
            </div>
            <span class="text-[10px] text-blue-600 font-bold uppercase">Database Sync</span>
          </div>

          <!-- Resume Select Dropdown -->
          <UFormGroup label="작성한 이력서 불러오기">
            <USelect
              v-model="selectedResumeId"
              :options="resumeOptions"
              placeholder="분석할 이력서를 선택해 주세요"
              size="md"
              class="w-full"
            />
          </UFormGroup>

          <UFormGroup label="이력서 텍스트 직접 입력/수정">
            <UTextarea
              v-model="resumeText"
              :rows="8"
              placeholder="이력서 목록에서 선택하거나, 여기에 이력서 텍스트를 직접 입력하세요..."
              class="w-full font-mono text-sm leading-relaxed"
            />
          </UFormGroup>
        </div>

        <div class="pt-4">
          <UButton
            color="blue"
            variant="solid"
            size="lg"
            block
            :loading="loading"
            :disabled="!jobTitle || !jobDescription || !resumeText"
            label="ATS 적합성 평가 실행"
            @click="runATSAnalysis"
            class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3.5 rounded-2xl hover:shadow-lg hover:shadow-blue-100 transition-all duration-200"
          />
        </div>
      </div>
    </div>

    <!-- Analysis Results Card -->
    <div v-if="result" class="bg-white border border-slate-100 rounded-3xl p-6 sm:p-10 shadow-md shadow-slate-100/50 space-y-8 relative overflow-hidden">
      <!-- Subtle top decorative gradient -->
      <div class="absolute inset-x-0 top-0 h-1.5 bg-gradient-to-r from-blue-500 to-indigo-600" />

      <!-- Overall score indicator -->
      <div class="flex flex-col md:flex-row items-center justify-between gap-6 pb-6 border-b border-slate-100">
        <div class="space-y-1 text-center md:text-left">
          <span class="text-[10px] font-bold uppercase tracking-wider text-blue-600 bg-blue-50 px-2.5 py-1 rounded-lg">분석 레포트</span>
          <h2 class="text-2xl font-extrabold text-slate-800 mt-2">{{ jobTitle }} 적합도 결과</h2>
        </div>
        <div class="flex items-center gap-4 bg-slate-50/60 border border-slate-100 rounded-2xl px-6 py-4">
          <div class="text-center md:text-right">
            <div class="text-xs font-bold text-slate-400 uppercase tracking-wider">최종 매칭률</div>
            <div class="text-4xl font-black text-blue-600 mt-1">{{ result.matchScore }}<span class="text-lg font-medium text-slate-400 ml-0.5">%</span></div>
          </div>
        </div>
      </div>

      <!-- Grid Breakdown Scores -->
      <div v-if="result.detailedBreakdown" class="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div class="p-5 rounded-2xl bg-slate-50/50 border border-slate-100/50 text-center space-y-1">
          <div class="text-xs font-bold text-slate-400 uppercase tracking-wider">기술 스택 매칭</div>
          <div class="text-2xl font-extrabold text-slate-850">{{ result.detailedBreakdown.skillsScore }}%</div>
        </div>
        <div class="p-5 rounded-2xl bg-slate-50/50 border border-slate-100/50 text-center space-y-1">
          <div class="text-xs font-bold text-slate-400 uppercase tracking-wider">요구 경력 충족</div>
          <div class="text-2xl font-extrabold text-slate-850">{{ result.detailedBreakdown.experienceScore }}%</div>
        </div>
        <div class="p-5 rounded-2xl bg-slate-50/50 border border-slate-100/50 text-center space-y-1">
          <div class="text-xs font-bold text-slate-400 uppercase tracking-wider">학력 사항 부합</div>
          <div class="text-2xl font-extrabold text-slate-850">{{ result.detailedBreakdown.educationScore }}%</div>
        </div>
        <div class="p-5 rounded-2xl bg-slate-50/50 border border-slate-100/50 text-center space-y-1">
          <div class="text-xs font-bold text-slate-400 uppercase tracking-wider">키워드 밀도 지수</div>
          <div class="text-2xl font-extrabold text-slate-850">{{ result.detailedBreakdown.keywordDensityScore }}%</div>
        </div>
      </div>

      <!-- Keyword Analysis -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="p-6 rounded-2xl bg-green-50/20 border border-green-100/50 space-y-4">
          <div class="text-xs font-bold text-green-700 uppercase tracking-wider flex items-center gap-1.5">
            <span class="w-1.5 h-1.5 bg-green-600 rounded-full" />
            이력서 내 감지된 매칭 키워드 (Found)
          </div>
          <div v-if="result.foundKeywords && result.foundKeywords.length > 0" class="flex flex-wrap gap-2">
            <span v-for="(k, idx) in result.foundKeywords" :key="idx" class="px-2.5 py-1 text-xs font-semibold bg-green-50 text-green-700 border border-green-100/80 rounded-xl">
              {{ k }}
            </span>
          </div>
          <p v-else class="text-xs text-slate-400">매칭된 키워드가 존재하지 않습니다.</p>
        </div>

        <div class="p-6 rounded-2xl bg-red-50/20 border border-red-100/50 space-y-4">
          <div class="text-xs font-bold text-red-700 uppercase tracking-wider flex items-center gap-1.5">
            <span class="w-1.5 h-1.5 bg-red-600 rounded-full" />
            우대 요구사항 내 누락된 키워드 (Missing)
          </div>
          <div v-if="result.missingKeywords && result.missingKeywords.length > 0" class="flex flex-wrap gap-2">
            <span v-for="(k, idx) in result.missingKeywords" :key="idx" class="px-2.5 py-1 text-xs font-semibold bg-red-50 text-red-700 border border-red-100/80 rounded-xl">
              {{ k }}
            </span>
          </div>
          <p v-else class="text-xs text-slate-400">누락된 필수 키워드가 없습니다.</p>
        </div>
      </div>

      <!-- Actionable recommendations -->
      <div class="p-6 rounded-2xl bg-slate-50/50 border border-slate-100 space-y-4">
        <div class="text-xs font-bold text-slate-500 uppercase tracking-wider">
          💡 ATS 매칭률 향상을 위한 기재 개선 제언
        </div>
        <ul class="text-xs text-slate-650 space-y-2 list-disc list-inside">
          <li v-for="(rec, idx) in result.recommendations" :key="idx" class="leading-relaxed">
            {{ rec }}
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'

definePageMeta({ middleware: 'auth' })

const toast = useToast()

const jobTitle = ref('시니어 프론트엔드 개발자')
const jobDescription = ref('- Nuxt.js, Vue 3, TypeScript 실무 경험 3년 이상\n- SSR / SSG 및 성능 최적화 경험\n- CI/CD 파이프라인 및 Docker 경험 우대')
const resumeText = ref('')
const loading = ref(false)
const result = ref<any>(null)

// 1. 기존 DB에 저장된 이력서 목록조회
const { data: resumes } = await useFetch<any[]>('/api/resumes')
const selectedResumeId = ref('')

// 드롭다운 옵션 바인딩
const resumeOptions = computed(() => {
  if (!resumes.value) return []
  return resumes.value.map(r => ({
    label: r.title,
    value: r.id
  }))
})

// 이력서 선택 시 텍스트 영역에 본문 자동 주입
watch(selectedResumeId, (newId) => {
  const target = resumes.value?.find(r => r.id === newId)
  if (target) {
    resumeText.value = target.originalContent || ''
  }
})

// 2. 실서비스 ATS 분석 실행
async function runATSAnalysis() {
  loading.value = true
  result.value = null
  try {
    const res: any = await $fetch('/api/ats/analyze', {
      method: 'POST',
      body: {
        jobTitle: jobTitle.value,
        jobDescription: jobDescription.value,
        resumeText: resumeText.value,
        resumeId: selectedResumeId.value || null
      }
    })
    result.value = res.analysis
    toast.add({ title: 'ATS 매칭 분석 완료', description: '요구 스택 분석 레포트가 하단에 작성되었습니다.', color: 'green' })
  } catch (err: any) {
    toast.add({ title: 'ATS 분석 실패', description: err.data?.message || '서버 분석 중 오류가 발생했습니다.', color: 'red' })
  } finally {
    loading.value = false
  }
}
</script>
