// app/components/Sidebar.vue
<template>
  <!-- Desktop sidebar -->
  <aside class="hidden lg:flex flex-col h-full">
    <div class="px-3 pt-2 pb-1">
      <p class="text-[10px] font-bold text-gray-400 uppercase tracking-widest px-3">메뉴</p>
    </div>
    <nav class="flex-1 space-y-0.5 px-2">
      <NuxtLink
        v-for="item in navItems"
        :key="item.path"
        :to="item.path"
        class="flex items-center gap-3 px-3 py-2 rounded-xl text-sm transition-all group"
        :class="isActive(item.path)
          ? 'bg-blue-50 text-blue-700 font-semibold'
          : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50'"
      >
        <span class="text-base leading-none">{{ item.emoji }}</span>
        <span>{{ item.label }}</span>
        <span v-if="isActive(item.path)" class="ml-auto w-1.5 h-1.5 rounded-full bg-blue-500"></span>
      </NuxtLink>
    </nav>
    <div class="p-3 border-t border-gray-100 mt-2">
      <NuxtLink to="/settings" class="flex items-center gap-3 px-3 py-2 rounded-xl text-sm text-gray-500 hover:text-gray-900 hover:bg-gray-50 transition-all">
        <span class="text-base">⚙️</span>
        <span>설정</span>
      </NuxtLink>
    </div>
  </aside>
</template>

<script setup lang="ts">
const route = useRoute()

const navItems = [
  { label: '대시보드', path: '/', emoji: '🏠' },
  { label: '이력서', path: '/resume', emoji: '📄' },
  { label: '모의 면접', path: '/interview', emoji: '🎤' },
  { label: 'ATS 분석', path: '/ats', emoji: '🎯' },
  { label: '휴머나이저', path: '/humanizer', emoji: '✨' },
  { label: 'Q&A 생성', path: '/qa', emoji: '💡' },
  { label: '경력 관리', path: '/career', emoji: '🗂️' },
  { label: '포토스튜디오', path: '/studio', emoji: '🎨' },
  { label: '문서', path: '/docs', emoji: '📋' },
]

function isActive(path: string) {
  if (path === '/') return route.path === '/'
  return route.path.startsWith(path)
}
</script>

// src/components/Sidebar.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function Sidebar() {
  const pathname = usePathname();

  const navItems = [
    { label: '대시보드', path: '/', icon: '📊' },
    { label: 'AI 이력서 고도화', path: '/resume', icon: '📄' },
    { label: 'AI 실시간 모의면접', path: '/interview', icon: '🎙️' },
    { label: 'ATS 적합도 분석', path: '/ats', icon: '🎯' },
    { label: 'AI Humanizer', path: '/humanizer', icon: '✍️' },
    { label: '예상 질문 (Q&A)', path: '/qa', icon: '❓' },
    { label: '경력 히스토리', path: '/career', icon: '💼' },
    { label: 'AI 프로필 스튜디오', path: '/studio', icon: '📸' },
    { label: '문서 파서/검증', path: '/docs', icon: '📂' },
    { label: '커뮤니티', path: '/community', icon: '💬' },
    { label: '설정', path: '/settings', icon: '⚙️' },
  ];

  return (
    <aside className="w-64 bg-slate-900 border-r border-slate-800 flex flex-col h-full min-h-screen text-slate-300">
      <div className="p-4 border-b border-slate-800 flex items-center gap-2">
        <span className="text-xl">✨</span>
        <span className="font-bold text-white text-lg tracking-wide">Kairos Career OS</span>
      </div>

      <nav className="flex-1 p-4 space-y-1 overflow-y-auto">
        {navItems.map((item) => {
          const isActive = pathname === item.path || (item.path !== '/' && pathname.startsWith(item.path));
          return (
            <Link
              key={item.path}
              href={item.path}
              className={`flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors ${
                isActive
                  ? 'bg-indigo-600/20 text-indigo-400 border border-indigo-500/30'
                  : 'hover:bg-slate-800/60 text-slate-400 hover:text-slate-200'
              }`}
            >
              <span className="text-base">{item.icon}</span>
              <span>{item.label}</span>
            </Link>
          );
        })}
      </nav>

      <div className="p-4 border-t border-slate-800 text-xs text-slate-500 text-center">
        Kairos Next.js v15.0
      </div>
    </aside>
  );
}
